# ./.github/workflows/ci.yml

name: SALAMATBOT CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  verify-workspace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- NEW DEBUGGING STEP ---
      # This will list all files on the runner so we can see the exact structure
      - name: Display structure of checked-out files
        run: ls -R

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Backend Lint
        run: pnpm --filter backend lint

      - name: Run Backend Build
        run: pnpm --filter backend build

      - name: Run Frontend Lint
        run: pnpm --filter frontend lint

      - name: Run Frontend Build
        run: pnpm --filter frontend build