# ./.github/workflows/ci.yml

name: SALAMATBOT CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  verify-workspace:
    runs-on: ubuntu-latest

    # --- ADD THIS BLOCK ---
    defaults:
      run:
        working-directory: ./SalamatBot
    # ----------------------

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # We need to check out the code INTO the directory we are working from
        with:
          path: './SalamatBot'

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          # Tell the cache where to find the lockfile now
          cache-dependency-path: './SalamatBot/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Backend Lint
        run: pnpm --filter backend lint

      - name: Run Backend Build
        run: pnpm --filter backend build

      - name: Run Frontend Lint
        run: pnpm --filter frontend lint

      - name: Run Frontend Build
        run: pnpm --filter frontend build