# ./.github/workflows/ci.yml

name: SALAMATBOT CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  verify-workspace:
    runs-on: ubuntu-latest

    # This is the key: Tell all subsequent 'run' commands
    # to execute inside the nested directory that checkout creates.
    defaults:
      run:
        working-directory: ./SalamatBot

    steps:
      - name: Checkout repository
        # This will create the 'SalamatBot' directory we need
        uses: actions/checkout@v4
        with:
          path: 'SalamatBot'

      # The following steps now automatically run inside './SalamatBot'
      # thanks to the 'defaults' block above.

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: './SalamatBot/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Backend Lint
        run: pnpm --filter backend lint

      - name: Run Backend Build
        run: pnpm --filter backend build

      - name: Run Frontend Lint
        run: pnpm --filter frontend lint

      - name: Run Frontend Build
        run: pnpm --filter frontend build