# ./.github/workflows/ci.yml

name: SALAMATBOT CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  verify-workspace:
    runs-on: ubuntu-latest
    # NO 'defaults' block is needed anymore. We will run everything from the root.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # We REMOVED the 'with: path:' block.
        # This checks out the code directly into the workspace root.

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          # The path is now simple because we are at the root.
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Backend Lint
        run: pnpm --filter backend lint

      - name: Run Backend Build
        run: pnpm --filter backend build

      - name: Run Frontend Lint
        run: pnpm --filter frontend lint

      - name: Run Frontend Build
        run: pnpm --filter frontend build